// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIrF7NqQTFkR-SXnvU-AJ2P2-_InW3Dg',
    appId: '1:235325238399:web:f494d0926b211a1c30e34a',
    messagingSenderId: '235325238399',
    projectId: 'planitpoker-ab425',
    authDomain: 'planitpoker-ab425.firebaseapp.com',
    storageBucket: 'planitpoker-ab425.appspot.com',
    measurementId: 'G-P7GLCBEK0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2BVCpCiLM_uKOwzIdzFZBu8QA0ph9g_I',
    appId: '1:235325238399:android:42d78edea0b4eaef30e34a',
    messagingSenderId: '235325238399',
    projectId: 'planitpoker-ab425',
    storageBucket: 'planitpoker-ab425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzh9-KnFst9AkhLdfZQs8F5w7nRV5APo',
    appId: '1:235325238399:ios:336d1842966568ae30e34a',
    messagingSenderId: '235325238399',
    projectId: 'planitpoker-ab425',
    storageBucket: 'planitpoker-ab425.appspot.com',
    iosBundleId: 'com.example.planitpoker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzh9-KnFst9AkhLdfZQs8F5w7nRV5APo',
    appId: '1:235325238399:ios:336d1842966568ae30e34a',
    messagingSenderId: '235325238399',
    projectId: 'planitpoker-ab425',
    storageBucket: 'planitpoker-ab425.appspot.com',
    iosBundleId: 'com.example.planitpoker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYIrF7NqQTFkR-SXnvU-AJ2P2-_InW3Dg',
    appId: '1:235325238399:web:74dfeeff9bffdf0d30e34a',
    messagingSenderId: '235325238399',
    projectId: 'planitpoker-ab425',
    authDomain: 'planitpoker-ab425.firebaseapp.com',
    storageBucket: 'planitpoker-ab425.appspot.com',
    measurementId: 'G-74WQZ71Y3R',
  );
}
